YurtOtomasyonu/Controllers/GiderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using YurtOtomasyonu.Models.Managers;
using YurtOtomasyonu.Models.mGiderler;
using YurtOtomasyonu.ViewModels.GiderListele;

namespace YurtOtomasyonu.Controllers
{
    [Authorize]
    public class GiderController : Controller
    {
        // GET: Gider
        
        public ActionResult Ekle()
        {
            
            return View();

        }
             [HttpPost]
        
        public ActionResult Ekle(Giderler giderler)
        {

            DatabaseContext db = new DatabaseContext();
            giderler.tarih = DateTime.Now;
            db.Giderler.Add(giderler);
            int result = db.SaveChanges();
            if (result > 0)
            {
                ViewBag.Result = "Giderler Kaydedilmiştir.";
                ViewBag.Status = "success";
            }
            else
            {
                ViewBag.Result = "Giderler Kaydedilememiştir.";
                ViewBag.Status = "danger";
            }
            

            return View();
        }
        
        public ActionResult Listele()
        {

            DatabaseContext db = new DatabaseContext();



            GiderListViewModel model = new GiderListViewModel();

            model.Giderler = db.Giderler.ToList();
            return View(model);
        }
        
        public ActionResult Guncelle() { 
        

            return View();
        }

    }
}

YurtOtomasyonu/Views/Gider/Ekle.cshtml
@model YurtOtomasyonu.Models.mGiderler.Giderler
@{
    ViewBag.Title = "Ekle";
    Layout = "~/Views/ThemeLayout/layout_one_theme.cshtml";
}

<h2>Ekle</h2>
@using (Html.BeginForm())
{

    <div class="input-group">
        <span class="input-group-addon" id="txtElektrik">Elektrik</span>

        @Html.TextBoxFor(x => x.elektrik, new { @class = "form-control", placeholder = "Elektrik", aria_describedby = "txtElektrik" })

    </div>
    <br />
    <div class="input-group">
        <span class="input-group-addon" id="txtSu">Su</span>

        @Html.TextBoxFor(x => x.su, new { @class = "form-control", placeholder = "Su", aria_describedby = "txtSu" })

    </div>
    <br />
    <div class="input-group">
        <span class="input-group-addon" id="txtDogalgaz">Doğalgaz</span>

        @Html.TextBoxFor(x => x.dogalgaz, new { @class = "form-control", placeholder = "Doğalgaz", aria_describedby = "txtDogalgaz" })

    </div>
    <br />
    <div class="input-group">
        <span class="input-group-addon" id="txtYemekhane">Yemekhane</span>

        @Html.TextBoxFor(x => x.yemekhane, new { @class = "form-control", placeholder = "Yemekhane", aria_describedby = "txtYemekhane" })

    </div>
    
    
    <br />
    <div class="input-group">
        <span class="input-group-addon" id="txtMaas">Personel Maaşı</span>

        @Html.TextBoxFor(x => x.calisan_maas, new { @class = "form-control", placeholder = "Personel Maaşı", aria_describedby = "txtMaas" })

    </div>




    <br />
    <div class="input-group">
        <input type="submit" value="Kaydet" class="btn btn-success" />
    </div>
    <br />
    <div class=" input-group-addon" style=" border">
        @if (ViewBag.Result != null)
        {
            <div class="alert alert-@ViewBag.Status" role="alert">
                @ViewBag.Result
            </div>
        }

    </div>
}

YurtOtomasyonu/Views/Gider/Guncelle.cshtml
@{
    ViewBag.Title = "Guncelle";
    Layout = "~/Views/ThemeLayout/layout_one_theme.cshtml";
}

<h2>Guncelle</h2>

YurtOtomasyonu/Views/Gider/Listele.cshtml
@using YurtOtomasyonu.ViewModels.GiderListele;
@model  GiderListViewModel
@{
    ViewBag.Title = "Listele";
    Layout = "~/Views/ThemeLayout/layout_one_theme.cshtml";
}

<h2>Gider Listele</h2>

<div class="container-fluid">




    <div class="row">
        <div class="col-md-12">


            <hr />

            <div>
                &nbsp;&nbsp;&nbsp;&nbsp; @Html.ActionLink("Gider Ekle", "Ekle", "Gider", null, new { @class = "btn btn-primary" })

            </div>
            <br />

            <div class="col-md-2">

                <ul class="list-group">
                    <li class="list-group-item active">
                        Elektrik
                    </li>
                    @foreach (var gider in Model.Giderler)
                    {

                        <li class="list-group-item">


                            @Html.ActionLink("Sil", "Sil", "Gider", new { giderID = gider.gider_ID }, new { @class = "btn btn-danger btn-xs" })
                            @(gider.elektrik + " TL")



                        </li>

                    }
                </ul>

            </div>
            <div class="col-md-2">

                <ul class="list-group">
                    <li class="list-group-item active">
                        Doğalgaz
                    </li>
                    @foreach (var gider in Model.Giderler)
                    {

                        <li class="list-group-item">


                            @Html.ActionLink("Giderler", "Sil", "Gider", new { giderID = gider.gider_ID }, new { @class = "btn btn-light btn-xs" })
                            @(gider.dogalgaz + " TL")



                        </li>

                    }
                </ul>

            </div>

            <div class="col-md-2">

                <ul class="list-group">
                    <li class="list-group-item active">
                        Su
                    </li>
                    @foreach (var gider in Model.Giderler)
                    {

                        <li class="list-group-item">


                            @Html.ActionLink("Giderler", "Sil", "Gider", new { giderID = gider.gider_ID }, new { @class = "btn btn-light btn-xs" })
                            @(gider.su + " 0TL")



                        </li>

                    }
                </ul>

            </div>

            <div class="col-md-2">

                <ul class="list-group">
                    <li class="list-group-item active">
                        Personel Maaş
                    </li>
                    @foreach (var gider in Model.Giderler)
                    {

                        <li class="list-group-item">


                            @Html.ActionLink("Maas", "Sil", "Gider", new { giderID = gider.gider_ID }, new { @class = "btn btn-light btn-xs" })
                            @(gider.calisan_maas + " TL")



                        </li>

                    }
                </ul>

            </div>
            <div class="col-md-3">

                <ul class="list-group">
                    <li class="list-group-item active">
                        TARİH
                    </li>
                    @foreach (var gider in Model.Giderler)
                    {

                        <li class="list-group-item">


                            @Html.ActionLink("Tarih", "Sil", "Gider", new { giderID = gider.gider_ID }, new { @class = "btn btn-light btn-xs" })
                            @(gider.tarih)



                        </li>

                    }
                </ul>

            </div>


            @*<div class="col-md-3">

            <ul class="list-group">
                <li class="list-group-item active">
                    TC Kimlik No
                </li>
                @foreach (var ogrenci in Model.Ogrenciler)
                {
                    <li class="list-group-item">
                        @Html.ActionLink("TC: ", "OgrListele", "Ogrenci", new { @class = "btn btn-light btn-xs" })
                        @(ogrenci.TC)
                    </li>
                }
            </ul>

        </div>*@






            @*<div class="col-md-6">

            <ul class="list-group">
                <li class="list-group-item active">
                    Adres
                </li>
                @foreach (var ogrenci in Model.Ogrenciler)
                {
                    <li class="list-group-item">
                        @Html.ActionLink("Adres: ", "OgrListele", "Ogrenci", new { @class = "btn btn-light btn-xs" })
                        @(ogrenci.Adres)

                    </li>
                }
            </ul>

        </div>*@



        </div>
    </div>
</div>